import sys
import os
import torch
import numpy as np
import cv2
import matplotlib.pyplot as plt

# import model and data feeder
from models.resnet_gcn_attention import ResNet_GCN_Attention
from feeder.feeder_nucla_fusion import Feeder

# To avoid "graph module not found" error during dynamic import in CTRGCN
sys.path.append('./')

def normalize_map(m):
    m = m - m.min()
    m = m / (m.max() + 1e-7)
    return m

def visualize_attention(data_path, output_dir='./visualizations'):
    os.makedirs(output_dir, exist_ok=True)
    print(f"Loading data from {data_path}...")
    
    # 1. Initialize the Feeder (Dataset)
    feeder = Feeder(
        data_path=data_path,
        split='val',
        debug=True, 
        random_choose=False,
        random_shift=False,
        random_move=False,
        window_size=52,
        normalization=False,
        temporal_rgb_frames=5 # We are loading 5 RGB frames per sample
    )
    
    # Get a few samples
    print("\nInitializing ResNet_GCN_Attention Model...")
    model = ResNet_GCN_Attention(
        num_class=10, 
        num_point=20, 
        num_person=1, 
        graph='graph.ucla.Graph',
        graph_args={'labeling_mode': 'spatial'},
        in_channels_gcn=3,
        in_channels_rgb=15, 
        drop_out=0,
        adaptive=True,
        freeze_gcn=True
    )
    model.eval()
    
    # Try to load pretrained weights for GCN to get meaningful attention
    # Without trained Spatial-Attention weights, the 7x7 map will look random,
    # but we can still visualize the mechanism.
    try:
        weights = torch.load('./result/nucla/CTROGC-GCN.pt')
        model.gcn.load_state_dict(weights)
        print("Pretrained GCN weights loaded successfully.")
    except Exception as e:
        print(f"Note: Pretrained GCN weights not loaded ({e}).")
        
    # We will process 3 different samples to see the effect
    for sample_idx in range(3):
        data, label, index = feeder[sample_idx]
        x_gcn = torch.tensor(data[0]).unsqueeze(0).float() # [1, 3, 52, 20, 1]
        x_rgb = torch.tensor(data[1]).unsqueeze(0).float() # [1, 15, 224, 224]
        
        print(f"\nProcessing Sample {sample_idx+1} (Label: {label})...")
        
        with torch.no_grad():
            # Extract GCN features and compute spatial mask
            f_gcn, _ = model.gcn.extract_feature(x_gcn) 
            f_gcn = f_gcn.mean(dim=(2, 3, 4)) # [1, 256]
            
            # This is the 1x1x7x7 mask that tells ResNet WHERE to look
            sp_att_weights = model.spatial_attention(f_gcn) # [1, 49]
            sp_att_weights = sp_att_weights.view(-1, 1, 7, 7) # [1, 1, 7, 7]
            
            # Convert to numpy for visualization
            spatial_mask = sp_att_weights[0, 0].numpy() # [7, 7]
            
            # The spatial mask is 7x7. We need to resize it to 224x224 to overlay it on the image
            spatial_mask_resized = cv2.resize(spatial_mask, (224, 224), interpolation=cv2.INTER_CUBIC)
            spatial_mask_normalized = normalize_map(spatial_mask_resized)
            
            # Apply color map
            heatmap = cv2.applyColorMap(np.uint8(255 * spatial_mask_normalized), cv2.COLORMAP_JET)
            heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB) # Convert to RGB for matplotlib
            
            # Now, let's look at the RGB frames.
            # x_rgb is [1, 15, 224, 224], which is 5 frames of 3 channels (RGB) stacked together
            frames_tensor = x_rgb[0].view(5, 3, 224, 224) 
            
            # We will plot the middle frame (frame 2) as the representative frame
            frame = frames_tensor[2].permute(1, 2, 0).numpy()
            
            # The images in the feeder are usually normalized (e.g. ImageNet mean/std) or in [0, 1] / [0, 255]
            # Let's cleanly map to [0, 1] for visualization
            frame = normalize_map(frame)
            
            # Create an overlaid image: Original Frame + Heatmap
            overlay = frame * 0.5 + (heatmap / 255.0) * 0.5
            
            # Plot
            fig, axs = plt.subplots(1, 3, figsize=(15, 5))
            fig.suptitle(f"Sample {sample_idx+1} (Action Label: {label}) - Spatial Attention Mechanism", fontsize=16)
            
            axs[0].imshow(frame)
            axs[0].set_title("1. Original RGB Frame")
            axs[0].axis('off')
            
            axs[1].imshow(heatmap)
            axs[1].set_title("2. Spatial Attention Mask (7x7 -> 224x224)\n(Generated by GCN from Skeleton)")
            axs[1].axis('off')
            
            axs[2].imshow(overlay)
            axs[2].set_title("3. Overlaid Result\n(What ResNet sees after multiplication)")
            axs[2].axis('off')
            
            save_path = os.path.join(output_dir, f'attention_sample_{sample_idx}.png')
            plt.savefig(save_path, bbox_inches='tight')
            plt.close()
            print(f"Saved visualization to {save_path}")
            
    print(f"\nAll visualizations completed. Check the '{output_dir}' folder.")

if __name__ == '__main__':
    data_path = r'C:\Users\nguyn\Downloads\NW-UCLA-ALL\NW-UCLA-ALL'
    visualize_attention(data_path)
