work_dir: ./work_dir/nucla/cross_modal_attention

# feeder
feeder: feeder.feeder_nucla_fusion.Feeder
train_feeder_args:
  data_path: ../drive/MyDrive/Data/NW-UCLA-ALL
  split: train
  debug: False
  random_choose: True
  random_shift: True
  random_move: True
  window_size: 52
  normalization: False
  temporal_rgb_frames: 5

test_feeder_args:
  data_path: ../drive/MyDrive/Data/NW-UCLA-ALL
  split: val
  debug: False
  temporal_rgb_frames: 5
  window_size: 52

# model
model: models.resnet_gcn_attention.ResNet_GCN_Attention
model_args:
  num_class: 10
  num_point: 20
  num_person: 1
  graph: graph.ucla.Graph
  graph_args:
    labeling_mode: "spatial"
  drop_out: 0
  in_channels_gcn: 3
  in_channels_rgb: 15
  adaptive: True
  freeze_gcn: True

# load pretrained weights for GCN component
weights: ./result/nucla/CTROGC-GCN.pt

# optim
weight_decay: 0.0004
base_lr: 0.0001 # Reduced to prevent Resnet overfitting
lr_decay_rate: 0.5
step: [15, 30]
optimizer: Adam

# training
device: [0]
batch_size: 16
test_batch_size: 32
num_epoch: 80
nesterov: True
eval_interval: 1
save_interval: 5
save_result: True
