# python main.py recognition_rgb_fused -c config/nucla/resnet_fused.yaml
work_dir: ./work_dir/nucla/resnet_fused

skeleton_joints_pkl: result/nucla/joint_result_msg3d.pkl
skeleton_bones_pkl: result/nucla/bone_result_msg3d.pkl

# feeder
feeder: feeder.feeder_rgb_fused_nucla.Feeder
train_feeder_args:
  random_choose: False
  random_move: True
  centralization: False
  window_size: -1
  random_interval: True
  random_roi_move: False
  random_flip: True
  temporal_rgb_frames: 5
  data_path: C:/Users/nguyn/Downloads/NW-UCLA-ALL/NW-UCLA-ALL
  label_path: train
  rgb_path: C:/ucla_stroi/
test_feeder_args:
  centralization: False
  temporal_rgb_frames: 5
  data_path: C:/Users/nguyn/Downloads/NW-UCLA-ALL/NW-UCLA-ALL
  label_path: val
  rgb_path: C:/ucla_stroi/

# model
model: models.resnet_only.Model
model_args:
  num_class: 10
  pretrained: True

stgcn_args:
  in_channels: 3
  num_class: 10
  edge_importance_weighting: True
  graph: graph.ucla.Graph
  graph_args:
    labeling_mode: "spatial"

# training
temporal_positions: 15
fix_weights: False
teacher_model: models.stgcn.Model
joint_weights: ./result/nucla/ST_GCN.pt
device: [0]
base_lr: 0.1
step: [10, 50]
num_epoch: 80
batch_size: 64
test_batch_size: 64
